### ISSUE TITLE
Compare Not Working as Wanted 

### ISSUE THREAD

**Issue by stevekessler** [stevekessler/CNA#1]
@rod4president I did the process we discussed but one of the folders for sure and maybe other changes did not come over when I pushed the new branch I created called "working".

The files are now at  /var/www/CNA/CNA still on Test2. 

Please advise on how to best get everything over in the new branch so I can compare.  

Thanks,
Steve

**Comment by rod4president** [comment]
Did you execute a ````git add .```` before committing and pushing?
Otherwise newly added files and directories would not be included.  You can
see if there's anything pending by using ````git status````

**Comment by stevekessler** [comment]
I did do the git add and if I do the git status I get

# On branch working
nothing to commit (working directory clean)


On Mon, Aug 3, 2015 at 6:39 AM, Rod McLennan <notifications@github.com>
wrote:

> Did you execute a ````git add .```` before committing and pushing?
> Otherwise newly added files and directories would not be included. You can
> see if there's anything pending by using ````git status````
>
> On Sun, Aug 2, 2015 at 10:12 PM, Steve Kessler <notifications@github.com>
> wrote:
>
> > Assigned #1 <https://github.com/stevekessler/CNA/issues/1> to
> > @rod4president <https://github.com/rod4president>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/stevekessler/CNA/issues/1#event-371604646>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevekessler/CNA/issues/1#issuecomment-127219290>.
>



-- 
Steve Kessler
Owner and Lead Consultant
Denver DataMan, LLC
303-587-4428

**Comment by stevekessler** [comment]
One other related note - when I look at the comparison between the files it just showing me the cache files because it cannot shoe me all files changed.  Can I use github to compare just a specific directory? I tried this and it did not work. 

![image](https://cloud.githubusercontent.com/assets/867985/9043157/aae6d4a8-39d0-11e5-99ca-2eacf621248d.png)

**Comment by rod4president** [comment]
Do you know where the modified files are approximately?

**Comment by stevekessler** [comment]
/home/steve has a web_old folder this has the issues and
the  coloradononprofits.org_current folder has the issues resolved.

These same folders are also in /var/www/CNA with the CNA folder being the
repo. All of the files are in CNA in to branches like you suggested.  There
is at least one folder that is not going up to GitHub and it appears to be
realted to the issue. The folder comes from the working version of the site
is called aspnet_client

Hope this helps.

Thanks!

On Tue, Aug 4, 2015 at 10:57 AM, Rod McLennan <notifications@github.com>
wrote:

> Do you know where the modified files are approximately?
>
> On Mon, Aug 3, 2015 at 11:13 AM, Steve Kessler <notifications@github.com>
> wrote:
>
> > One other related note - when I look at the comparison between the files
> > it just showing me the cache files because it cannot shoe me all files
> > changed. Can I use github to compare just a specific directory? I tried
> > this and it did not work.
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/867985/9043157/aae6d4a8-39d0-11e5-99ca-2eacf621248d.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/stevekessler/CNA/issues/1#issuecomment-127334788>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevekessler/CNA/issues/1#issuecomment-127675506>.
>



-- 
Steve Kessler
Owner and Lead Consultant
Denver DataMan, LLC
303-587-4428

**Comment by rod4president** [comment]
There is nothing in the aspnet_client folder (and sub-folders) on any branch or in the coloradononprofits.org_current folder.  Maybe that's your issue.

It also appears you have a git root at /var/www as well as /var/www/CNA/CNA.  I'm not sure if you were aware of that.

**Comment by stevekessler** [comment]
CNA/CNA is the got root.

Do you have any idea to focus in on the specific doffs I need because it
just showing me the wrong things (HTML cache files) and says there are too
many changes to show.

Thanks,
Steve

On Tuesday, August 4, 2015, Rod McLennan <notifications@github.com> wrote:

> There is nothing in the aspnet_client folder (and sub-folders) on any
> branch or in the coloradononprofits.org_current folder. Maybe that's your
> issue.
>
> It also appears you have a git root at /var/www as well as
> /var/www/CNA/CNA. I'm not sure if you were aware of that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevekessler/CNA/issues/1#issuecomment-127700724>.
>


-- 
Steve Kessler
Owner and Lead Consultant
Denver DataMan, LLC
303-587-4428

**Comment by rod4president** [comment]
You can diff a specific folder from the command line pretty easily.  For example if you are on the ````master```` branch at the site root.  You can type ````git diff working -- ./wp-admin```` to check the diff in the wp-admin folder.  Check out this: http://www.git-scm.com/docs/git-diff

**Comment by stevekessler** [comment]
But not using the visual tools on github?

On Tuesday, August 4, 2015, Rod McLennan <notifications@github.com> wrote:

> You can diff a specific folder from the command line pretty easily. For
> example if you are on the master branch at the site root. You can type git
> diff working -- ./wp-admin to check the diff in the wp-admin folder.
> Check out this: http://www.git-scm.com/docs/git-diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stevekessler/CNA/issues/1#issuecomment-127706178>.
>


-- 
Steve Kessler
Owner and Lead Consultant
Denver DataMan, LLC
303-587-4428

**Comment by rod4president** [comment]
I don't believe you can do it on GitHub.

**Comment by rod4president** [comment]
You can try removing the cache folder from both branches and see if that helps.  Or creating a couple branches with only the folder(s) you care about.
